// Build-time tool: extracts CPU/feature tables from LLVM's MCSubtargetInfo
// and emits them as standalone C/C++ data files with no LLVM dependency.
//
// Usage: gen_target_tables <triple> > target_tables_<arch>.h
//
// This tool links against LLVM at build time, but the output files do not.

#include "llvm/Config/llvm-config.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Support/InitLLVM.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/raw_ostream.h"

#include <algorithm>
#include <memory>
#include <string>
#include <vector>

using namespace llvm;

static std::unique_ptr<MCSubtargetInfo> getSTI(const Triple &TT) {
    std::string Error;
    const Target *TheTarget = TargetRegistry::lookupTarget(TT.str(), Error);
    if (!TheTarget) {
        errs() << "Error: " << Error << "\n";
        return nullptr;
    }
    return std::unique_ptr<MCSubtargetInfo>(
        TheTarget->createMCSubtargetInfo(TT.str(), "generic", ""));
}

// Get features for a specific CPU
static FeatureBitset getFeaturesForCPU(const Triple &TT, StringRef CPU) {
    std::string Error;
    const Target *TheTarget = TargetRegistry::lookupTarget(TT.str(), Error);
    if (!TheTarget) return {};
    auto STI = std::unique_ptr<MCSubtargetInfo>(
        TheTarget->createMCSubtargetInfo(TT.str(), CPU, ""));
    if (!STI) return {};
    return STI->getFeatureBits();
}

static void emitHeader(raw_ostream &OS, StringRef Arch) {
    OS << "// Auto-generated by gen_target_tables from LLVM's TableGen data.\n";
    OS << "// DO NOT EDIT - regenerate with: gen_target_tables <triple>\n";
    OS << "//\n";
    OS << "// Derived from LLVM Project data (Apache License v2.0 with LLVM Exceptions).\n";
    OS << "// See https://llvm.org/LICENSE.txt for details.\n";
    OS << "//\n";
    OS << "// No LLVM runtime dependency.\n\n";

    std::string Guard = "TARGET_TABLES_" + Arch.upper() + "_H";
    OS << "#ifndef " << Guard << "\n";
    OS << "#define " << Guard << "\n\n";
    OS << "#include <stdint.h>\n";
    OS << "#include <stddef.h>\n";
    OS << "#include <string.h>\n\n";
    OS << "#if defined(__GNUC__) || defined(__clang__)\n";
    OS << "#define CPUFEATURES_UNUSED __attribute__((unused))\n";
    OS << "#else\n";
    OS << "#define CPUFEATURES_UNUSED\n";
    OS << "#endif\n\n";
}

static void emitFooter(raw_ostream &OS, StringRef Arch) {
    std::string Guard = "TARGET_TABLES_" + Arch.upper() + "_H";
    OS << "#endif // " << Guard << "\n";
}

// Emit the feature bitset type
static void emitBitsetType(raw_ostream &OS, unsigned NumWords) {
    OS << "// Feature bitset: " << NumWords << " x uint64_t = "
       << (NumWords * 64) << " bits\n";
    OS << "#define TARGET_FEATURE_WORDS " << NumWords << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_MAJOR " << LLVM_VERSION_MAJOR << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_MINOR " << LLVM_VERSION_MINOR << "\n";
    OS << "#define TARGET_TABLES_LLVM_VERSION_PATCH " << LLVM_VERSION_PATCH << "\n\n";
    OS << "typedef struct {\n";
    OS << "    uint64_t bits[TARGET_FEATURE_WORDS];\n";
    OS << "} FeatureBits;\n\n";

    OS << "static inline int feature_test(const FeatureBits *fb, unsigned bit) {\n";
    OS << "    return (fb->bits[bit / 64] >> (bit % 64)) & 1;\n";
    OS << "}\n\n";

    OS << "static inline void feature_set(FeatureBits *fb, unsigned bit) {\n";
    OS << "    fb->bits[bit / 64] |= (1ULL << (bit % 64));\n";
    OS << "}\n\n";

    OS << "static inline void feature_clear(FeatureBits *fb, unsigned bit) {\n";
    OS << "    fb->bits[bit / 64] &= ~(1ULL << (bit % 64));\n";
    OS << "}\n\n";

    OS << "static inline void feature_or(FeatureBits *dst, const FeatureBits *src) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] |= src->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_and(FeatureBits *dst, const FeatureBits *src) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] &= src->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_andnot(FeatureBits *dst, const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] = a->bits[i] & ~b->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline void feature_and_out(FeatureBits *dst, const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        dst->bits[i] = a->bits[i] & b->bits[i];\n";
    OS << "}\n\n";

    OS << "static inline int feature_any(const FeatureBits *fb) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        if (fb->bits[i]) return 1;\n";
    OS << "    return 0;\n";
    OS << "}\n\n";

    OS << "static inline unsigned feature_popcount(const FeatureBits *fb) {\n";
    OS << "    unsigned count = 0;\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        count += __builtin_popcountll(fb->bits[i]);\n";
    OS << "    return count;\n";
    OS << "}\n\n";

    OS << "static inline int feature_equal(const FeatureBits *a, const FeatureBits *b) {\n";
    OS << "    for (int i = 0; i < TARGET_FEATURE_WORDS; i++)\n";
    OS << "        if (a->bits[i] != b->bits[i]) return 0;\n";
    OS << "    return 1;\n";
    OS << "}\n\n";
}

static void emitFeatureBits(raw_ostream &OS, const FeatureBitset &Bits, unsigned NumWords) {
    OS << "{ { ";
    for (unsigned i = 0; i < NumWords; i++) {
        uint64_t Word = 0;
        for (unsigned j = 0; j < 64; j++) {
            unsigned Bit = i * 64 + j;
            if (Bit < Bits.size() && Bits.test(Bit))
                Word |= (1ULL << j);
        }
        if (i > 0) OS << ", ";
        OS << "0x" << Twine::utohexstr(Word) << "ULL";
    }
    OS << " } }";
}

static FeatureBitset computeHWMask(ArrayRef<SubtargetFeatureKV> Features,
                                    ArrayRef<SubtargetSubTypeKV> CPUs) {
    // A feature is "hardware" if it appears in some CPU's Implies
    // (ISA features set by the CPU definition) but NOT only in TuneImplies
    // (scheduling/tuning hints). This works for all architectures without
    // needing host CPU detection.

    FeatureBitset ImpliedByAnyCPU;
    FeatureBitset TuneOnlyBits;

    // Collect all bits that appear in any CPU's Implies
    for (const auto &CPU : CPUs) {
        ImpliedByAnyCPU |= CPU.Implies.getAsBitset();
    }

    // Collect all bits that appear ONLY in TuneImplies (never in Implies)
    for (const auto &CPU : CPUs) {
        TuneOnlyBits |= CPU.TuneImplies.getAsBitset();
    }

    // Hardware = implied by some CPU, but not exclusively a tuning feature.
    // Also include features that are implied by other hardware features
    // (via the feature implication chain).
    FeatureBitset HWMask = ImpliedByAnyCPU & ~(TuneOnlyBits & ~ImpliedByAnyCPU);

    // Also add any feature that is implied by a hardware feature
    for (const auto &F : Features) {
        if (HWMask.test(F.Value)) {
            HWMask |= F.Implies.getAsBitset();
        }
    }

    return HWMask;
}

static void emitFeatureTable(raw_ostream &OS,
                              ArrayRef<SubtargetFeatureKV> Features,
                              ArrayRef<SubtargetSubTypeKV> CPUs,
                              unsigned NumWords) {
    FeatureBitset HWMask = computeHWMask(Features, CPUs);

    OS << "// Feature table: name, description, bit index, implied features, is_hw\n";
    OS << "typedef struct {\n";
    OS << "    const char *name;\n";
    OS << "    const char *desc;\n";
    OS << "    unsigned bit;         // feature bit index\n";
    OS << "    unsigned char is_hw;  // 1 = hardware feature, 0 = tuning/mode hint\n";
    OS << "    FeatureBits implies;  // transitively implied features\n";
    OS << "} FeatureEntry;\n\n";

    // Exclude features that shouldn't affect sysimage target matching.
    // Uppercase names are system register features (aarch64).
    // The blacklist covers tuning hints and privileged instructions that
    // differ between Intel/AMD but don't affect user-space codegen.
    static const char *blacklist[] = {
        // x86: tuning hints and privileged instructions
        "ermsb", "fsrm",   // tuning hints (REP MOVS speed)
        "nopl",            // baseline assumption, not CPUID-detectable
        "invpcid",         // privileged TLB instruction
        "pconfig",         // privileged platform configuration instruction
        "wbnoinvd",        // privileged cache writeback instruction
        "hreset",          // privileged history-reset instruction
        // aarch64:
        "ssbs",            // speculative execution mitigation, not codegen-relevant.
        nullptr
    };
    for (const auto &F : Features) {
        if (F.Key[0] && std::isupper(static_cast<unsigned char>(F.Key[0])))
            HWMask.reset(F.Value);
        for (const char **bl = blacklist; *bl; bl++) {
            if (F.Key == *bl) {
                HWMask.reset(F.Value);
                break;
            }
        }
    }

    OS << "static const FeatureEntry feature_table[] = {\n";
    for (const auto &F : Features) {
        bool IsHW = HWMask.test(F.Value);
        OS << "    { \"" << F.Key << "\", \"";
        StringRef Desc(F.Desc);
        for (char C : Desc) {
            if (C == '"') OS << "\\\"";
            else if (C == '\\') OS << "\\\\";
            else OS << C;
        }
        OS << "\", " << F.Value << ", " << (IsHW ? "1" : "0") << ", ";
        emitFeatureBits(OS, F.Implies.getAsBitset(), NumWords);
        OS << " },\n";
    }
    OS << "};\n\n";
    OS << "static const unsigned num_features = "
       << Features.size() << ";\n\n";

    // Emit precomputed hardware feature mask
    OS << "// Precomputed mask of hardware (CPUID-detectable) features\n";
    OS << "static const FeatureBits hw_feature_mask = ";
    emitFeatureBits(OS, HWMask, NumWords);
    OS << ";\n\n";
}

static void emitCPUTable(raw_ostream &OS,
                          const Triple &TT,
                          ArrayRef<SubtargetSubTypeKV> CPUs,
                          ArrayRef<SubtargetFeatureKV> Features,
                          unsigned NumWords) {
    OS << "// CPU table: name, base features (from Implies), full resolved features\n";
    OS << "typedef struct {\n";
    OS << "    const char *name;\n";
    OS << "    FeatureBits implies;       // direct feature bits from TableGen\n";
    OS << "    FeatureBits tune_implies;  // tuning feature bits\n";
    OS << "    FeatureBits features;      // fully resolved features (transitive closure)\n";
    OS << "} CPUEntry;\n\n";

    OS << "static const CPUEntry cpu_table[] = {\n";
    for (const auto &CPU : CPUs) {
        // Get the fully resolved features for this CPU
        FeatureBitset Resolved = getFeaturesForCPU(TT, CPU.Key);

        OS << "    { \"" << CPU.Key << "\",\n";
        OS << "      ";
        emitFeatureBits(OS, CPU.Implies.getAsBitset(), NumWords);
        OS << ",\n      ";
        emitFeatureBits(OS, CPU.TuneImplies.getAsBitset(), NumWords);
        OS << ",\n      ";
        emitFeatureBits(OS, Resolved, NumWords);
        OS << " },\n";
    }
    OS << "};\n\n";
    OS << "static const unsigned num_cpus = "
       << CPUs.size() << ";\n\n";
}

// Emit a feature enum for convenient access
static void emitFeatureEnum(raw_ostream &OS,
                             ArrayRef<SubtargetFeatureKV> Features) {
    OS << "// Feature bit indices\n";
    OS << "enum FeatureIndex {\n";
    for (const auto &F : Features) {
        // Create a C-safe identifier from the feature name
        std::string Name = "FEAT_";
        for (char C : StringRef(F.Key)) {
            if (C == '-' || C == '.') Name += '_';
            else Name += toupper(C);
        }
        OS << "    " << Name << " = " << F.Value << ",\n";
    }
    OS << "};\n\n";
}

// Emit a lookup function
static void emitLookupFunctions(raw_ostream &OS) {
    OS << "// Binary search for a feature by name (table is sorted)\n";
    OS << "CPUFEATURES_UNUSED static const FeatureEntry *find_feature(const char *name) {\n";
    OS << "    int lo = 0, hi = (int)num_features - 1;\n";
    OS << "    while (lo <= hi) {\n";
    OS << "        int mid = (lo + hi) / 2;\n";
    OS << "        int cmp = strcmp(feature_table[mid].name, name);\n";
    OS << "        if (cmp == 0) return &feature_table[mid];\n";
    OS << "        if (cmp < 0) lo = mid + 1;\n";
    OS << "        else hi = mid - 1;\n";
    OS << "    }\n";
    OS << "    return NULL;\n";
    OS << "}\n\n";

    OS << "// Binary search for a CPU by name (table is sorted)\n";
    OS << "// Use find_cpu() instead — this is the raw lookup without alias resolution.\n";
    OS << "CPUFEATURES_UNUSED static const CPUEntry *_find_cpu_exact(const char *name) {\n";
    OS << "    int lo = 0, hi = (int)num_cpus - 1;\n";
    OS << "    while (lo <= hi) {\n";
    OS << "        int mid = (lo + hi) / 2;\n";
    OS << "        int cmp = strcmp(cpu_table[mid].name, name);\n";
    OS << "        if (cmp == 0) return &cpu_table[mid];\n";
    OS << "        if (cmp < 0) lo = mid + 1;\n";
    OS << "        else hi = mid - 1;\n";
    OS << "    }\n";
    OS << "    return NULL;\n";
    OS << "}\n\n";

    OS << "// Expand implied features transitively\n";
    OS << "CPUFEATURES_UNUSED static void expand_implied(FeatureBits *bits) {\n";
    OS << "    int changed = 1;\n";
    OS << "    while (changed) {\n";
    OS << "        changed = 0;\n";
    OS << "        for (unsigned i = 0; i < num_features; i++) {\n";
    OS << "            if (feature_test(bits, feature_table[i].bit)) {\n";
    OS << "                FeatureBits old = *bits;\n";
    OS << "                feature_or(bits, &feature_table[i].implies);\n";
    OS << "                if (!feature_equal(bits, &old)) changed = 1;\n";
    OS << "            }\n";
    OS << "        }\n";
    OS << "    }\n";
    OS << "}\n\n";
}

int main(int argc, char **argv) {
    InitLLVM X(argc, argv);

    LLVMInitializeX86TargetInfo();
    LLVMInitializeX86TargetMC();
    LLVMInitializeAArch64TargetInfo();
    LLVMInitializeAArch64TargetMC();
    LLVMInitializeRISCVTargetInfo();
    LLVMInitializeRISCVTargetMC();

    if (argc < 2) {
        errs() << "Usage: " << argv[0] << " <triple>\n";
        errs() << "  e.g.: " << argv[0] << " x86_64-unknown-linux-gnu\n";
        return 1;
    }

    Triple TT(Triple::normalize(argv[1]));
    std::string Arch = TT.getArchName().str();

    auto STI = getSTI(TT);
    if (!STI) return 1;

    auto Features = STI->getAllProcessorFeatures();
    auto CPUs = STI->getAllProcessorDescriptions();

    // Determine number of 64-bit words needed for feature bitset
    unsigned MaxBit = 0;
    for (const auto &F : Features)
        MaxBit = std::max(MaxBit, F.Value);
    unsigned NumWords = (MaxBit / 64) + 1;

    raw_fd_ostream &OS = outs();

    emitHeader(OS, Arch);
    OS << "#include <string.h>\n\n";
    OS << "// Generated for triple: " << TT.str() << "\n";
    OS << "// " << Features.size() << " features, " << CPUs.size() << " CPUs\n\n";

    emitBitsetType(OS, NumWords);
    emitFeatureEnum(OS, Features);
    emitFeatureTable(OS, Features, CPUs, NumWords);
    emitCPUTable(OS, TT, CPUs, Features, NumWords);
    emitLookupFunctions(OS);
    emitFooter(OS, Arch);

    return 0;
}
